# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecm < Formula
  desc "Merge multiple kubeconfig"
  homepage "https://github.com/sunny0826/kubecm"
  version "0.16.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.2/kubecm_0.16.2_Darwin_x86_64.tar.gz"
      sha256 "60a93b9bc6bbcbe58193452d909bf23cd60f745dd5ecc12a21d5e0fec1b8f0f7"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.2/kubecm_0.16.2_Darwin_arm64.tar.gz"
      sha256 "508d373d7ee7c5ebae9304f9b5456f2c823f96a5f00fecec5274941e77529c7a"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.2/kubecm_0.16.2_Linux_x86_64.tar.gz"
      sha256 "51503d9f69a7ac9cc8621bd8dc04929c4bd8fe5e6d82e4a5bbfd8197d0b09207"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.2/kubecm_0.16.2_Linux_arm64.tar.gz"
      sha256 "bb57c3c453f9b53161a806e58220247f6282a5c2b483fa5a30e4eca12ff1fb5d"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/kubecm version"
  end
end
