# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecm < Formula
  desc "Merge multiple kubeconfig"
  homepage "https://github.com/sunny0826/kubecm"
  version "0.13.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sunny0826/kubecm/releases/download/v0.13.1/kubecm_0.13.1_Darwin_x86_64.tar.gz"
    sha256 "de9df950776923f97c98e580df1d89f27d8aa22228fcaa5aed48ff2823654a59"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sunny0826/kubecm/releases/download/v0.13.1/kubecm_0.13.1_Linux_x86_64.tar.gz"
    sha256 "57a8150faa688ee9197fab715924966f07604ea092628269fdf90be9d83b5ce9"
  end

  depends_on "git"

  def install
    bin.install "kubecm"

    # Install bash completion
    output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
    (bash_completion/"kubecm").write output

    # Install zsh completion
    output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
    (zsh_completion/"_kubecm").write output
  end

  test do
    system "#{bin}/kubecm version"
  end
end
