# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecm < Formula
  desc "Merge multiple kubeconfig"
  homepage "https://github.com/sunny0826/kubecm"
  version "0.16.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.3/kubecm_0.16.3_Darwin_x86_64.tar.gz"
      sha256 "ea9ae4cb24427c3216c9ee1b10eb9b8e30acf69b82631d541e038b047c26ac6b"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.3/kubecm_0.16.3_Darwin_arm64.tar.gz"
      sha256 "2e0cd17e3af8ed845dd01ea2c1f4ba8043f287b170ba3e50a38b02f76f9b8d0f"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.3/kubecm_0.16.3_Linux_arm64.tar.gz"
      sha256 "60ca5aefa4aadc3920fe9419289820cd5b36838c86fc34b2d5d5e07b142ae3a6"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sunny0826/kubecm/releases/download/v0.16.3/kubecm_0.16.3_Linux_x86_64.tar.gz"
      sha256 "fa0af358394caeed0b9c54de3a0bd5599f70d3f1eefafb1f653da698096871ed"

      def install
        bin.install "kubecm"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "bash")
        (bash_completion/"kubecm").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/kubecm", "completion", "zsh")
        (zsh_completion/"_kubecm").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/kubecm version"
  end
end
